// @generated by cargo run -p rc-log-api --bin typegen_models
// Do not edit manually.

export type RatingDto = "one" | "two" | "three" | "four" | "five"

export type PerformedVariationDto = { performedVariationId: string; variationId: string; quality: RatingDto; comfort: RatingDto; repeatability: RatingDto; note: string | null }
