// @generated by cargo run -p rc-log-api --bin typegen_models
// Do not edit manually.

export type TypeDto = "Helicopter" | "Plane" | "Drone"

export type RatingDto = "one" | "two" | "three" | "four" | "five"

export type PerformedVariationDto = { performedVariationId: string; variationId: string; maneuverName: string | null; variationName: string | null; quality: RatingDto; comfort: RatingDto; repeatability: RatingDto }

export type SessionDto = { id: string; userId: string; date: string; modelId: string | null; modelName: string | null; modelType: TypeDto | null; modelPhotoAssetId: string | null; performedVariations: PerformedVariationDto[] }
