// @generated by cargo run -p rc-log-api --bin typegen_models
// Do not edit manually.

export type SessionDto = { id: string; userId: string; date: string; modelId: string | null; note: string | null }
