// @generated by cargo run -p rc-log-api --bin typegen_models
// Do not edit manually.

export type QualityDto = "one" | "two" | "three" | "four" | "five"

export type ComfortDto = "one" | "two" | "three" | "four" | "five"

export type RepeatabilityDto = "one" | "two" | "three" | "four" | "five"
