[workspace]
resolver = "3"
members = ["crates/api", "crates/application", "crates/domain", "crates/persistance"]

[workspace.dependencies]
rc-log-api = { path = "crates/api" }
rc-log-application = { path = "crates/application" }
rc-log-domain = { path = "crates/domain" }
rc-log-persistance = { path = "crates/persistance" }

axum = { version = "0.8.8" }
argon2 = { version = "0.5.3" }
jsonwebtoken = { version = "10.3.0" }
thiserror = { version = "2.0.18" }
sqlx = { version = "0.8.6" }
uuid = { version = "1.22.0" }
serde = { version = "1.0.228" }
serde_json = { version = "1.0.149" }
tokio = { version = "1.50.0" }
dotenvy = { version = "0.15.7" }
tracing = { version = "0.1.44" }
tracing-subscriber = { version = "0.3.23" }
tower-http = { version = "0.6.8" }
moka = { version = "0.12.15" }
image = { version = "0.25.10" }
chrono = { version = "0.4.44" }
specta = { version = "1.0.5" }
specta-serde = { version = "0.0.11" }
specta-typescript = { version = "0.0.11" }