[workspace]
resolver = "3"
members = ["crates/api", "crates/application", "crates/domain", "crates/persistance"]

[workspace.dependencies]
rc-log-api = { path = "crates/api" }
rc-log-application = { path = "crates/application" }
rc-log-domain = { path = "crates/domain" }
rc-log-persistance = { path = "crates/persistance" }

axum = { version = "0.8.8" }
thiserror = { version = "2.0.18" }
sqlx = { version = "0.8" }
uuid = { version = "1.22.0", features = ["v4"] }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
tokio = { version = "1" }
dotenvy = { version = "0.15" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
tower-http = { version = "0.6.8" }

