// @generated by cargo run -p rc-log-api --bin typegen_models
// Do not edit manually.

export type TypeDto = "Helicopter" | "Plane" | "Drone"

export type ModelDto = { id: string; ownerId: string; name: string; type: TypeDto; photoAssetId: string | null }
