// @generated by cargo run -p rc-log-api --bin typegen_models
// Do not edit manually.

export type PhotoPathsDto = { id: string; smallPath: string; mediumPath: string | null; largePath: string | null }
