// @generated by cargo run -p rc-log-api --bin typegen_models
// Do not edit manually.

export type TypeDto = "Helicopter" | "Plane" | "Drone"

export type DifficultyDto = "level1" | "level2" | "level3" | "level4" | "level5" | "level6" | "level7"

export type TagDto = { id: string; name: string }

export type VariationDto = { id: string; name: string; description: string; videoAssetId: string; difficulty: DifficultyDto }

export type ManeuverDto = { id: string; modelType: TypeDto; name: string; tags: TagDto[]; description: string; minDifficulty: DifficultyDto; maxDifficulty: DifficultyDto; defaultVariation: VariationDto; variations: VariationDto[] }
