#!/usr/bin/env python3
"""
generate_seed.py — Generate idempotent PostgreSQL seed SQL for maneuvers.

Reads all content from content/maneuver/ and produces INSERT … ON CONFLICT
upsert statements in the correct dependency order:

  1. maneuver.tag
  2. maneuver.maneuver
  3. maneuver.maneuver_tag  (DELETE + INSERT — no unique id column to conflict on)
  4. asset.video
  5. maneuver.variation

Asset paths stored in the DB are relative to RC_LOG_ASSET_PATH, e.g.:
  videos/helicopter_hover_default_small.mp4

Usage:
  python scripts/generate_seed.py [-o output.sql]

  -o / --output   Write SQL to this file instead of stdout.

Run from the repository root.
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTENT_DIR = REPO_ROOT / "content" / "maneuver"
TAGS_FILE = CONTENT_DIR / "tags.json"

REQUIRED_MANEUVER_FIELDS = {"id", "model_type", "name", "tags", "description"}
REQUIRED_VARIATION_FIELDS = {"id", "videoAssetName", "videoAssetId", "name", "description", "difficulty"}


def load_tags() -> dict[str, str]:
    """Return mapping of tag name → tag id from tags.json."""
    if not TAGS_FILE.exists():
        print(f"ERROR: {TAGS_FILE} not found.", file=sys.stderr)
        sys.exit(1)
    with open(TAGS_FILE, encoding="utf-8") as f:
        tags = json.load(f)
    return {tag["name"]: tag["id"] for tag in tags}


def escape_sql_string(value: str) -> str:
    """Escape a string for use as a PostgreSQL literal (single-quote doubling)."""
    return value.replace("'", "''")


def sql_str(value: str) -> str:
    return f"'{escape_sql_string(value)}'"


def load_maneuver(maneuver_dir: Path) -> dict:
    path = maneuver_dir / "maneuver.json"
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    missing = REQUIRED_MANEUVER_FIELDS - data.keys()
    if missing:
        print(
            f"ERROR: {path.relative_to(REPO_ROOT)} is missing fields: {missing}",
            file=sys.stderr,
        )
        sys.exit(1)
    return data


def load_variation(variation_dir: Path) -> dict:
    path = variation_dir / "variation.json"
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    missing = REQUIRED_VARIATION_FIELDS - data.keys()
    if missing:
        print(
            f"ERROR: {path.relative_to(REPO_ROOT)} is missing fields: {missing}",
            file=sys.stderr,
        )
        sys.exit(1)
    data["_dir_name"] = variation_dir.name
    return data


def collect_data(tag_registry: dict[str, str]) -> tuple[list, list]:
    """
    Returns (maneuvers, variations) where each entry contains fully resolved data.
    Validates that all referenced tags exist in the registry.
    """
    maneuvers = []
    variations = []

    for maneuver_dir in sorted(CONTENT_DIR.iterdir()):
        if not maneuver_dir.is_dir():
            continue
        maneuver = load_maneuver(maneuver_dir)
        if maneuver is None:
            continue

        # Validate tags
        for tag_name in maneuver["tags"]:
            if tag_name not in tag_registry:
                print(
                    f"ERROR: tag '{tag_name}' in "
                    f"{maneuver_dir.name}/maneuver.json not found in tags.json. "
                    "Add it to content/maneuver/tags.json first.",
                    file=sys.stderr,
                )
                sys.exit(1)

        maneuver["_dir_name"] = maneuver_dir.name
        maneuvers.append(maneuver)

        for variation_dir in sorted(maneuver_dir.iterdir()):
            if not variation_dir.is_dir():
                continue
            variation = load_variation(variation_dir)
            if variation is None:
                continue
            variation["_maneuver_id"] = maneuver["id"]
            variation["_is_default"] = variation_dir.name == "default"
            variations.append(variation)

    return maneuvers, variations


def generate_sql(maneuvers: list, variations: list, tag_registry: dict[str, str]) -> str:
    lines = []

    lines.append("-- ============================================================")
    lines.append("-- rc-log seed SQL — generated by scripts/generate_seed.py")
    lines.append("-- Safe to re-run: all statements are idempotent upserts.")
    lines.append("-- ============================================================")
    lines.append("")

    # ------------------------------------------------------------------ tags --
    lines.append("-- 1. Tags")
    for tag_name, tag_id in sorted(tag_registry.items(), key=lambda x: x[1]):
        lines.append(
            f"INSERT INTO maneuver.tag (id, name)"
            f" VALUES ('{tag_id}', {sql_str(tag_name)})"
            f" ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;"
        )
    lines.append("")

    # -------------------------------------------------------------- maneuvers --
    lines.append("-- 2. Maneuvers")
    for m in maneuvers:
        lines.append(
            f"INSERT INTO maneuver.maneuver (id, model_type, name, description)"
            f" VALUES ("
            f"'{m['id']}', "
            f"{sql_str(m['model_type'])}, "
            f"{sql_str(m['name'])}, "
            f"{sql_str(m['description'])}"
            f")"
            f" ON CONFLICT (id) DO UPDATE SET"
            f"  model_type = EXCLUDED.model_type,"
            f"  name = EXCLUDED.name,"
            f"  description = EXCLUDED.description;"
        )
    lines.append("")

    # ---------------------------------------------------------- maneuver_tags --
    lines.append("-- 3. Maneuver–tag associations (delete + re-insert for clean upsert)")
    for m in maneuvers:
        mid = m["id"]
        lines.append(f"DELETE FROM maneuver.maneuver_tag WHERE maneuver_id = '{mid}';")
        for tag_name in m["tags"]:
            tid = tag_registry[tag_name]
            lines.append(
                f"INSERT INTO maneuver.maneuver_tag (maneuver_id, tag_id)"
                f" VALUES ('{mid}', '{tid}');"
            )
    lines.append("")

    # ---------------------------------------------------------- asset.video ---
    lines.append("-- 4. Video assets")
    for v in variations:
        asset_name = v["videoAssetName"]
        asset_id = v["videoAssetId"]
        small  = f"videos/{asset_name}_small.mp4"
        medium = f"videos/{asset_name}_medium.mp4"
        large  = f"videos/{asset_name}_large.mp4"
        lines.append(
            f"INSERT INTO asset.video (id, name, small_path, medium_path, large_path)"
            f" VALUES ("
            f"'{asset_id}', "
            f"{sql_str(asset_name)}, "
            f"{sql_str(small)}, "
            f"{sql_str(medium)}, "
            f"{sql_str(large)}"
            f")"
            f" ON CONFLICT (id) DO UPDATE SET"
            f"  name = EXCLUDED.name,"
            f"  small_path = EXCLUDED.small_path,"
            f"  medium_path = EXCLUDED.medium_path,"
            f"  large_path = EXCLUDED.large_path;"
        )
    lines.append("")

    # ---------------------------------------------------------- variations ----
    lines.append("-- 5. Variations")
    for v in variations:
        is_default_sql = "TRUE" if v["_is_default"] else "FALSE"
        lines.append(
            f"INSERT INTO maneuver.variation"
            f" (id, maneuver_id, name, description, video_asset_name, is_default, difficulty)"
            f" VALUES ("
            f"'{v['id']}', "
            f"'{v['_maneuver_id']}', "
            f"{sql_str(v['name'])}, "
            f"{sql_str(v['description'])}, "
            f"{sql_str(v['videoAssetName'])}, "
            f"{is_default_sql}, "
            f"{v['difficulty']}"
            f")"
            f" ON CONFLICT (id) DO UPDATE SET"
            f"  maneuver_id = EXCLUDED.maneuver_id,"
            f"  name = EXCLUDED.name,"
            f"  description = EXCLUDED.description,"
            f"  video_asset_name = EXCLUDED.video_asset_name,"
            f"  is_default = EXCLUDED.is_default,"
            f"  difficulty = EXCLUDED.difficulty;"
        )
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate idempotent PostgreSQL seed SQL for maneuvers."
    )
    parser.add_argument(
        "-o", "--output",
        metavar="FILE",
        help="Write SQL to FILE instead of stdout.",
    )
    args = parser.parse_args()

    if not CONTENT_DIR.exists():
        print(f"ERROR: content directory not found: {CONTENT_DIR}", file=sys.stderr)
        sys.exit(1)

    tag_registry = load_tags()
    maneuvers, variations = collect_data(tag_registry)

    if not maneuvers:
        print("ERROR: no maneuvers found under content/maneuver/.", file=sys.stderr)
        sys.exit(1)

    sql = generate_sql(maneuvers, variations, tag_registry)

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(sql)
        print(f"Seed SQL written to {out_path}")
    else:
        sys.stdout.write(sql)


if __name__ == "__main__":
    main()
